version: "3"

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: 123456789
    volumes:
      - ebay_alert_db:/var/lib/postgresql/data
    expose:
      - "5435"
    ports:
      - "5435:5435"
    command: -p 5435
  web:
    build: ""
    env_file:
      .env
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - 8000:8000
  redis:
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
    volumes:
      - .:/code/

volumes:
  ebay_alert_db: